### ISSUE TITLE
Crash caused by closing main window while a tkinter TopLevel window is still open.

### ISSUE THREAD

**Issue by trin5tensa** [trin5tensa/pigjar#380]
Simple dialogs in `guidialogs.py` appear to be unaffected. 
At first sight problem appears to be associated with the complex `while` loops used for high level validation of a `guidialogs` class  or subclass. Possible cause is shutting down `tk/tcl` and the program is unable to handle the loss. 

Error message from 'New Pig' menu item:
------------------------------------------
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Users\Stephen\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 1699, in `__call__`
    return self.func(*args)
  File "E:\Stephenff\Programming\WorkZone\pigjar\pigjar\pigmenu.py", line 64, in pig_new
    support.retry_cancel_dialog('GUI Missing Name')
  File "E:\Stephenff\Programming\WorkZone\pigjar\pigjar\support.py", line 145, in retry_cancel_dialog
    button_names=('retry', 'cancel'), )()
  File "E:\Stephenff\Programming\WorkZone\pigjar\pigjar\guidialogs.py", line 153, in `__call__`
    self.create_window()
  File "E:\Stephenff\Programming\WorkZone\pigjar\pigjar\guidialogs.py", line 164, in create_window
    self.window = tk.Toplevel(self.parent)
  File "D:\Users\Stephen\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 2336, in `__init__`
    BaseWidget.__init__(self, master, 'toplevel', cnf, {}, extra)
  File "D:\Users\Stephen\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 2293, in `__init__`
    (widgetName, self._w) + extra + self._options(cnf))
_tkinter.TclError: can't invoke "toplevel" command: application has been destroyed

**Comment by trin5tensa** [comment]
This appears to be behaving differently on a MacBook where it appears to go back to desktop without writing the datafile and without offering any error message.

**Comment by trin5tensa** [comment]
Related to #430 Create an input form for the 'from' account
Integration testing for #430 identified a race condition with similar symptoms. The window and its children were closed. Code which was expecting a substantive response from the GUIet  raised an exception when it failed to get an appropriate response.
